# Lazy git bolded highlight doesn't seem to work in Kitty?
# This adds background color instead.
gui:
  nerdFontsVersion: "2" 
  theme:
    lightTheme: false
    activeBorderColor:
      - white
      - bold
    inactiveBorderColor:
      - white
    selectedLineBgColor:
      - reverse
      - blue
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
keybinding:
  commits:
    moveDownCommit: '<c-s>' # move commit down one
    moveUpCommit: '<c-w>' # move commit up one
os:
  # editCommand: 'nvim'
  # editCommandTemplate: {{editor}} --server /tmp/nvim-server-$(tmux display-message -p '#S').pipe --remote-send "<cmd>lua require'scripts.lazygit-open-file'('{{filename}}', '{{line}}')<CR>"
  # editCommandTemplate: '{{editor}} --server ~/tmp/nvim-server.pipe --remote-tab "$(pwd)/{{filename}}"'
  # Connect to existing nvim instance if possible
  # edit: nvim --server /tmp/nvim-server-$(tmux display-message -p '#S').pipe --remote-send "<cmd>lua require'scripts.lazygit-open-file'('{{filename}}', '{{line}}')<CR>"
  # open: nvim --server /tmp/nvim-server-$(tmux display-message -p '#S').pipe --remote-send "<cmd>lua require'scripts.lazygit-open-file'('{{filename}}', '{{line}}')<CR>"
  edit: nvim --server /tmp/nvim-server-$(echo $TMUX_PANE).pipe --remote-send "<cmd>lua require'scripts.lazygit-open-file'('{{filename}}', '{{line}}')<CR>"
  open: nvim --server /tmp/nvim-server-$(echo $TMUX_PANE).pipe --remote-send "<cmd>lua require'scripts.lazygit-open-file'('{{filename}}', '{{line}}')<CR>"
