#!/bin/bash

# /home/<YOUR USERNAME>/.config/i3/scripts/

# PICTURE=/tmp/i3lock.png
# SCREENSHOT="scrot $PICTURE"
#
# BLUR="30x30"
#
# $SCREENSHOT
# convert $PICTURE -blur $BLUR $PICTURE
# i3lock -i $PICTURE
# rm $PICTURE
#
i3lock -c 000000
