code --install-extension adamhartford.vscode-base64
code --install-extension adrianwilczynski.namespace
code --install-extension alefragnani.Bookmarks
code --install-extension bierner.markdown-emoji
code --install-extension christian-kohler.path-intellisense
code --install-extension coolbear.systemd-unit-file
code --install-extension cschlosser.doxdocgen
code --install-extension dbaeumer.vscode-eslint
code --install-extension DotJoshJohnson.xml
code --install-extension EditorConfig.EditorConfig
code --install-extension fernandoescolar.vscode-solution-explorer
code --install-extension flesler.url-encode
code --install-extension foam.foam-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension Fudge.auto-using
code --install-extension GitHub.copilot
code --install-extension GrapeCity.gc-excelviewer
code --install-extension hashicorp.terraform
code --install-extension hbenl.vscode-test-explorer
code --install-extension heaths.vscode-guid
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension jflbr.jwt-decoder
code --install-extension johnpapa.vscode-peacock
code --install-extension jongrant.csharpsortusings
code --install-extension jsynowiec.vscode-insertdatestring
code --install-extension k--kato.docomment
code --install-extension kenhowardpdx.vscode-gist
code --install-extension kleber-swf.unity-code-snippets
code --install-extension mads-hartmann.bash-ide-vscode
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.live-server
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.test-adapter-converter
code --install-extension ms-vscode.vs-keybindings
code --install-extension mushan.vscode-paste-image
code --install-extension naumovs.color-highlight
code --install-extension Perkovec.emoji
code --install-extension PKief.material-icon-theme
code --install-extension quicktype.quicktype
code --install-extension qwtel.sqlite-viewer
code --install-extension redhat.java
code --install-extension ritwickdey.LiveServer
code --install-extension ryanluker.vscode-coverage-gutters
code --install-extension ryu1kn.partial-diff
code --install-extension sleistner.vscode-fileutils
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tintoy.msbuild-project-tools
code --install-extension Tobiah.unity-tools
code --install-extension twxs.cmake
code --install-extension Tyriar.vscode-terminal-here
code --install-extension viktorqvarfordt.vscode-pitch-black-theme
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension yy0931.go-to-next-error
code --install-extension yzhang.markdown-all-in-one
